common/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    re_path(r'^profile/(?P<pk>[0-9]+)/$',login_required(views.ProfileView.as_view()), name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from market.views import base_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('common/', include('common.urls')),
    path('', base_views.main, name='index'),  # '/' 에 해당되는 path
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # media 경로 추가

market/urls.py
from django.urls import path
from .views import base_views, product_views, comment_views

app_name = 'market'

urlpatterns = [
    # base_views.py
    path('Product/list/', base_views.index, name='index'),
    path('Product/list/<str:category_name>', base_views.index, name='index'),
    path('Product/detail/<int:product_id>/', base_views.detail, name='detail'),
    
    path('', base_views.main, name='main'),
    
    # product_views.py
    path('Product/create/', product_views.Product_create, name='Product_create'),
    path('Product/modify/<int:product_id>/', product_views.Product_modify, name='Product_modify'),
    path('Product/delete/<int:product_id>/', product_views.Product_delete, name='Product_delete'),
    path('liked_products/', product_views.liked_products_view, name='liked_products'),

    # comment_views.py
    path('Comment/create/<int:product_id>/', comment_views.Comment_create, name='Comment_create'),
    path('Comment/modify/<int:comment_id>/', comment_views.Comment_modify, name='Comment_modify'),
    path('Comment/delete/<int:comment_id>/', comment_views.Comment_delete, name='Comment_delete'),
    path('Product/vote/<int:product_id>/', product_views.Product_vote, name='Product_vote'),
    path('vote/Comment/<int:comment_id>/', comment_views.Comment_vote, name='Comment_vote'),
]

market/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.conf import settings


class Category(models.Model):
    name=models.CharField(max_length=20,unique=True)
    description=models.CharField(max_length=200,null=True,blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('market:index',args=[self.name])


class Product(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, null=True, default='', related_name='author_question')
    name = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='liked_products')  # 찜
    view_count = models.IntegerField(default=0)  # 조회수 필드
    price = models.IntegerField() #가격 필드
    image = models.ImageField(upload_to='images/', null=True, blank=True)  # 이미지 필드
    category=models.ForeignKey(Category,on_delete=models.CASCADE,related_name='category_question')

    def __str__(self):
        return self.subject


class Comment(models.Model):
    buyer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')


class ProductCount(models.Model):
    ip = models.CharField(max_length=30)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.ip


class Profile(models.Model):
    user=models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    profile_photo=models.ImageField(blank=True)

market/forms.py
from django import forms
from .models import Product, Comment


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product  # 사용할 모델
        fields = ['name', 'content', 'image', 'price', 'category']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'name': '제목',
            'content': '내용',
            'image': '이미지',
            'price': '가격',
            'category': '카테고리',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글',
        }

market/views/Commet_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import CommentForm
from ..models import Product, Comment


@login_required(login_url='common:login')
def Comment_create(request, Product_id):
    Product = get_object_or_404(Product, pk=Product_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            Comment = form.save(commit=False)
            Comment.buyer = request.user  # buyer 속성에 로그인 계정 저장
            Comment.create_date = timezone.now()
            Comment.Product = Product
            Comment.save()
            return redirect('{}#Comment_{}'.format(resolve_url('market:detail', Product_id=Product.id), Comment.id))
    else:
        form = CommentForm()
    context = {'Product': Product, 'form': form}
    return render(request, 'market/Product_detail.html', context)


@login_required(login_url='common:login')
def Comment_modify(request, Comment_id):
    Comment = get_object_or_404(Comment, pk=Comment_id)
    if request.user != Comment.buyer:
        messages.error(request, '수정권한이 없습니다')
        return redirect('market:detail', Product_id=Comment.Product.id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=Comment)
        if form.is_valid():
            Comment = form.save(commit=False)
            Comment.modify_date = timezone.now()
            Comment.save()
            return redirect('{}#Comment_{}'.format(resolve_url('market:detail', Product_id=Comment.Product.id), Comment.id))
    else:
        form = CommentForm(instance=Comment)
    context = {'Comment': Comment, 'form': form}
    return render(request, 'market/Comment_form.html', context)


@login_required(login_url='common:login')
def Comment_delete(request, Comment_id):
    Comment = get_object_or_404(Comment, pk=Comment_id)
    if request.user != Comment.buyer:
        messages.error(request, '삭제권한이 없습니다')
    else:
        Comment.delete()
    return redirect('{}#Comment_{}'.format(resolve_url('market:detail', Product_id=Comment.Product.id), Comment.id))


@login_required(login_url='common:login')
def Comment_vote(request, Comment_id):
    Comment = get_object_or_404(Comment, pk=Comment_id)
    if request.user in Comment.voter.all():
        Comment.voter.remove(request.user)
    else:
        Comment.voter.add(request.user)
    return redirect('market:detail', Product_id=Comment.Product.id)

market/views/Product_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import ProductForm
from ..models import Product, Category


@login_required(login_url='common:login')
def Product_create(request):
    category_list = Category.objects.all()

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.seller = request.user  # author 속성에 로그인 계정 저장
            product.create_date = timezone.now()
            product.price = form.cleaned_data['price']
            product.save()
            return redirect('market:index')
    else:
        form = ProductForm()
    context = {'form': form, 'category_list': category_list}
    return render(request, 'market/Product_form.html', context)


@login_required(login_url='common:login')
def Product_modify(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.user != product.seller:
        messages.error(request, '수정권한이 없습니다')
        return redirect('market:detail', product_id=product.id)
    if request.method == "POST":
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            product = form.save(commit=False)
            product.modify_date = timezone.now()  # 수정일시 저장
            product.save()
            return redirect('market:detail', product_id=product.id)
    else:
        form = ProductForm(instance=product)
    context = {'form': form, 'category':product.category}
    return render(request, 'market/Product_form.html', context)


@login_required(login_url='common:login')
def Product_delete(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.user != product.seller:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('market:detail', product_id=product.id)
    product.delete()
    return redirect('market:index')


@login_required(login_url='common:login')
def Product_vote(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.user == product.seller:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    elif request.user in product.voter.all():
        product.voter.remove(request.user)
    else:
        product.voter.add(request.user)
    return redirect('market:detail', product_id=product.id)


@login_required(login_url='common:login')
def liked_products_view(request):
    liked_products = Product.objects.filter(voter=request.user)
    return render(request, 'market/liked_products.html', {'liked_products': liked_products})

market/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from ..models import Product, ProductCount, Category


def get_client_ip(request):  # Add this function
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def index(request, category_name=''):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어

    category_list=Category.objects.all()
    if(category_name!=''):
        category = get_object_or_404(Category, name=category_name)
        product_list = Product.objects.filter(category=category)
    else:
        product_list = Product.objects.all()

    product_list = product_list.order_by('-create_date')

    if kw:
        product_list = product_list.filter(
            Q(name__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw)  # 내용 검색
        ).distinct()
    paginator = Paginator(product_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    if (category_name != ''):
        context = {'Product_list': page_obj, 'page': page, 'kw': kw, 'category_list': category_list, 'category': category}
    else:
        context = {'Product_list': page_obj, 'page': page, 'kw': kw, 'category_list': category_list}
    return render(request, 'market/Product_list.html', context)


def main(request):
    return render(request, 'market/mainpage.html')



def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    ip = get_client_ip(request)
    cnt = ProductCount.objects.filter(ip=ip, product=product).count()
    if cnt == 0:
        qc = ProductCount(ip=ip, product=product)
        qc.save()
        if product.view_count:
            product.view_count += 1
        else:
            product.view_count = 1
        product.save()
    context = {'product': product}
    return render(request, 'market/Product_detail.html', context)

market/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import CommentForm
from ..models import Product, Comment


@login_required(login_url='common:login')
def Comment_create(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.buyer = request.user  # buyer 속성에 로그인 계정 저장
            comment.create_date = timezone.now()
            comment.product = product
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('market:detail', product_id=product.id), comment.id))
    else:
        form = CommentForm()
    context = {'product': product, 'form': form}
    return render(request, 'market/Product_detail.html', context)


@login_required(login_url='common:login')
def Comment_modify(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.buyer:
        messages.error(request, '수정권한이 없습니다')
        return redirect('market:detail', product_id=comment.product.id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('market:detail', product_id=comment.product.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'comment': comment, 'form': form}
    return render(request, 'market/Comment_form.html', context)


@login_required(login_url='common:login')
def Comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.buyer:
        messages.error(request, '삭제권한이 없습니다')
    else:
        comment.delete()
    return redirect('{}#comment_{}'.format(resolve_url('market:detail', product_id=comment.product.id), comment.id))


@login_required(login_url='common:login')
def Comment_vote(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user in comment.voter.all():
        comment.voter.remove(request.user)
    else:
        comment.voter.add(request.user)
    return redirect('market:detail', product_id=comment.product.id)

templates/market/Comment_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/market/Product_detail.html
{% extends 'base.html' %}
{% load market_filter %}
{% load time_since %}
{% load humanize %}
{% block content %}

<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul>
            <li>{{ message.message }}</li>
        </ul>
        {% endfor %}
    </div>
    {% endif %}

<style>
    table {
        margin-left: auto;
        margin-right: auto;
        width: 800pt;
        height: 250pt;
    }

    table,
    th,
    td {
    }

    colgroup {
        width: 100%;
        height: 100%;
    }

    col.col1 {
        width: 0%;
    }

    col.col2 {
        width: 5%;
    }

    col.col3 {
        width: 90%;
    }

    .container {
        max-width: 80rem;
        margin: 0 auto;
    }

    .alert {
        padding: 1rem;
        margin-bottom: 1rem;
    }

    .card {
        border: 1px solid #ddd;
        border-radius: 4px;
    }

    .card-body {
        padding: 1rem;
        height: 130pt;
    }

    .card-text {
        margin-bottom: 1rem;
    }

    .badge {
        font-size: 0.8rem;
        padding: 0.25rem 0.5rem;
    }

    .my-3 {
        margin-top: 1rem;
        margin-bottom: 1rem;
        clear: both;
    }

    .btn {
        display: inline-block;
        padding: 0.25rem 0.5rem;
        font-size: 1.2rem;
        border-radius: 4px;
        text-decoration: none;
        cursor: pointer;
    }

    .btn-outline-secondary {
        color: #6c757d;
        border-color: #6c757d;
    }

    .btn-outline-secondary:hover {
        color: #fff;
        background-color: #6c757d;
        border-color: #6c757d;
    }

    .rounded-pill {
        border-radius: 50rem;
    }

    #left-section {
        width: 60%;
        padding: 10px;
        float: left;
    }

    #right-section {
        width: 40%;
        padding: 10px;
        float: right;
    }
</style>

    <p>&nbsp;</p>
<table>
    <colgroup>
        <col class="col1">
        <col class="col2">
        <col class="col3">
    </colgroup>
    <tbody>
        <tr>
            <td rowspan="5">
                <img src="{{ product.image.url }}" style="width: 500px; height: 500px" alt="{{ product.name }}"
                    class="my-3">
            </td>
            <td rowspan="5">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
            <td>
                <h1>{{ product.name }}</h1>
            </td>
        </tr>
        <tr>
            <td>
                <p class="border-bottom py-1">
                    <span style="font-size: 2.5rem; font-weight: bold;">{{ product.price|intcomma }}</span>
                    <span style="font-size: 1.5rem;">원</span>
                </p>
            </td>
        </tr>
        <td>
            <div class="d-flex">
                <div>
                    <p style="color: #C0C0C0;">♥: {{product.voter.count}} |&nbsp;</p>
                </div>
                <div>

                    <div>
                        <div style="color: #C0C0C0;">▶:{{ product.create_date|time_since }}</div>
                    </div>
                                {% if Product.view_count > 0 %}
                                    <div style="color: #C0C0C0;">조회수:{{ Product.view_count }}</span>
                                {% endif %}
                            </div>

        <tr>
            <td>
<p>&nbsp;</p><p>&nbsp;</p>
            </td>
        </tr>
        <tr>
            <td>
                <div class="my-3" style="display: flex; align-items: center;">
                    <a href="javascript:void(0)" data-uri="{% url 'market:Product_vote' product.id %}"
                        class="recommend btn btn-sm btn-outline-secondary"
                        style="background-color: blue; color: white; font-size: 2rem; font-weight: bold; padding: 0.5rem 1rem; padding-left: 4rem; padding-right: 4rem;">
                        ♥찜
                    </a>
                     &nbsp; &nbsp;
                                        <a href="javascript:void(0)" data-uri="{% url 'market:Product_vote' product.id %}"
                        class="recommend btn btn-sm btn-outline-secondary"
                        style=" font-size: 2rem; font-weight: bold; padding: 0.5rem 1rem; padding-left: 4rem; padding-right: 4rem;">
                        충톡
                    </a>

                </div>
                <div class="my-3" style="margin-left: auto;">
                        {% if request.user == comment.author %}
                        <a href="{% url 'market:Product_modify' product.id  %}"
                            class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                            data-uri="{% url 'market:Product_delete' product.id  %}">삭제</a>
                        {% endif %}
                    </div>
            </td>
        </tr>
        <tr>
        </tr>
    </tbody>
</table>





<!-- 답변 -->

<hr style="border: solid 1px black;">

<div class="row">
    <div class="col-md-4">
        <h5 class="border-bottom py-2">상품설명</h5>
        <div class="card my-3 left-section">
            <div class="card-body">
                <div class="card-text">
                    <h6 style="font-weight: bold;">{{ product.content|mark }}</h6>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-8">
        <h5 class="border-bottom py-2">{{product.comment_set.count}}개의 답변이 있습니다.</h5>
        <div class="answer-container">
            {% for comment in  product.comment_set.all %}
            <a id="comment_{{ comment.id }}"></a>
            <div class="answer-card card my-3">
                <div class="card-body">
                    <div class="answer-content card-text">
                        <span class="answer-author" style="font-weight: bold;">[ {{ comment.buyer.username }} ]</span>{{ comment.content|mark }}
                    </div>
                    <hr>
                    <div class="answer-meta">
                        {% if product.modify_date %}
                        <div class="badge bg-light text-dark p-2 text-start mx-3" style="border: 0.1px solid #000;font-size: 1.5rem;">
                            <div>수정됨: {{ comment.modify_date }}</div>
                        </div>
                        {% else %}
                        <div class="badge bg-light text-dark p-2 text-start mx-3" style="border: 0.5px solid #000;font-size: 1.5rem;">
                            <div>{{ comment.create_date }}</div>
                        </div>
                        {% endif %}
                        <div class="answer-buttons my-3">
                            <a href="javascript:void(0)" data-uri="{% url 'market:Comment_vote' comment.id  %}"
                                class="recommend btn btn-sm btn-outline-secondary"> 추천
                                <span class="badge rounded-pill bg-success">{{comment.voter.count}}</span>
                            </a>
                            {% if request.user == comment.author %}
                            <a href="{% url 'market:Comment_modify' comment.id  %}"
                                class="btn btn-sm btn-outline-secondary">수정</a>
                            <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                                data-uri="{% url 'market:Comment_delete' comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>


<style>
    .answer-container {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between;
    }

    .answer-card {
        flex-basis: 100%; /* 원하는 카드 너비로 조정 */
        margin-bottom: 20px;
        padding: 15px;
        border: 1px solid #ddd;
        border-radius: 4px;
        background-color: #f9f9f9;
        overflow: auto; /* 스크롤 생성 */
    }

    .answer-content {
        margin-bottom: 10px;
        max-height: 200px;
    }

    .answer-meta {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 10px;
    }

    .answer-meta .badge {
        font-size: 0.8rem;
        padding: 0.25rem 0.5rem;
    }

    .answer-buttons {
        display: flex;
    }

    .answer-buttons .btn {
        margin-right: 5px;
    }

    .left-section {
        padding: 10px;
    }

    .right-section {
        padding: 10px;
    }
</style>




<form action="{% url 'market:Comment_create' product.id %}" method="post" class="my-3">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="mb-3">
        <label for="content" class="form-label">답변내용</label>
        <textarea {% if not user.is_authenticated %}disabled{% endif %}
                  name="content" id="content" class="form-control" rows="10"></textarea>
    </div>
    <input type="submit" value="답변등록" class="btn btn-primary">
</form>
</div>
{% endblock %}
{% block script %}


<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

templates/market/Product_list.html
{% extends 'base.html' %}
{% load market_filter %}
{% load time_since %}
{% load humanize %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'market:Product_create' %}" class="btn btn-primary">상품등록</a>
        </div>
    </div>
    <hr>
    <h2>
        {% if category %}
        {{ category.description }}
        {% else %}
        최근 올라온 상품
        {% endif %}
    </h2>
    <div class="row">
        <div class="col-sm-12 col-md-3 col-lg-2 p-2">
            <!-- Sidebar  -->
            <nav id="sidebar" class="border-top border-secondary">
                <div class="list-group">
                    {% for cat in category_list %}
                        {% if cat == category %}
                            <a class="rounded-0 list-group-item list-group-item-action list-group-item-light active"
                               href="{{ cat.get_absolute_url }}">{{ cat.description }}</a>
                        {% else %}
                            <a class="rounded-0 list-group-item list-group-item-action list-group-item-light"
                               href="{{ cat.get_absolute_url }}">{{ cat.description }}</a>
                        {% endif %}
                    {% endfor %}
                </div>
            </nav>
        </div>
        {% if Product_list %}
        {% for Product in Product_list %}
        <div class="col-3">
            <a href="{% url 'market:detail' Product.id %}" style="text-decoration: none; color: inherit;">
                <div class="item">
                    {% if Product.image %}
                        <img src="{{ Product.image.url }}" style="width:200px; height:200px; border:1px solid #eaeaea; padding: 0px; border-radius: 10px;" alt="{{ Product.name }}">
                    {% endif %}
                    <div class="card p-1" style="width: 200px;">
                        <p class="name" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">{{ Product.name }}</p>
                        <div style="display: flex; justify-content: space-between;">
                            <span class="price" style="font-weight: 500;"><strong>{{ Product.price|intcomma }}원</strong></span>
                            <span class="time" style="font-size: 12px; text-align:right">{{ Product.create_date|time_since }}</span>
                        </div>
                    </div>
                </div>
            </a>
            <br>
        </div>
        {% endfor %}
        {% else %}
            <div class="col">
                <p>제품이 없습니다.</p>
            </div>
        {% endif %}
    </div>
</div>

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if Product_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ Product_list.previous_page_number }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in Product_list.paginator.page_range %}
        {% if page_number >= Product_list.number|add:-5 and page_number <= Product_list.number|add:5 %}
        {% if page_number == Product_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if Product_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ Product_list.next_page_number }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    </div>
    <form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}