common/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    re_path(r'^profile/(?P<pk>[0-9]+)/$',login_required(views.ProfileView.as_view()), name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from market.views import base_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
    path('common/', include('common.urls')),
    path('', base_views.main, name='index'),  # '/' 에 해당되는 path
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # media 경로 추가

market/urls.py
from django.urls import path
from .views import base_views, product_views, comment_views

app_name = 'market'

urlpatterns = [
    # base_views.py
    path('Product/list/', base_views.index, name='index'),
    path('Product/list/<str:category_name>', base_views.index, name='index'),
    path('Product/detail/<int:product_id>/', base_views.detail, name='detail'),
    
    path('', base_views.main, name='main'),
    
    # product_views.py
    path('Product/create/', product_views.Product_create, name='Product_create'),
    path('Product/modify/<int:product_id>/', product_views.Product_modify, name='Product_modify'),
    path('Product/delete/<int:product_id>/', product_views.Product_delete, name='Product_delete'),
    path('liked_products/', product_views.liked_products_view, name='liked_products'),

    # comment_views.py
    path('Comment/create/<int:product_id>/', comment_views.Comment_create, name='Comment_create'),
    path('Comment/modify/<int:comment_id>/', comment_views.Comment_modify, name='Comment_modify'),
    path('Comment/delete/<int:comment_id>/', comment_views.Comment_delete, name='Comment_delete'),
    path('Product/vote/<int:product_id>/', product_views.Product_vote, name='Product_vote'),
    path('vote/Comment/<int:comment_id>/', comment_views.Comment_vote, name='Comment_vote'),
]

market/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from ..models import Product, ProductCount, Category


def get_client_ip(request):  # Add this function
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def index(request, category_name=''):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어

    category_list=Category.objects.all()
    if(category_name!=''):
        category = get_object_or_404(Category, name=category_name)
        product_list = Product.objects.filter(category=category)
    else:
        product_list = Product.objects.all()

    product_list = product_list.order_by('-create_date')

    if kw:
        product_list = product_list.filter(
            Q(name__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw)  # 내용 검색
        ).distinct()
    paginator = Paginator(product_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    if (category_name != ''):
        context = {'Product_list': page_obj, 'page': page, 'kw': kw, 'category_list': category_list, 'category': category}
    else:
        context = {'Product_list': page_obj, 'page': page, 'kw': kw, 'category_list': category_list}
    return render(request, 'market/Product_list.html', context)


def main(request):
    return render(request, 'market/mainpage.html')



def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    ip = get_client_ip(request)
    cnt = ProductCount.objects.filter(ip=ip, product=product).count()
    if cnt == 0:
        qc = ProductCount(ip=ip, product=product)
        qc.save()
        if product.view_count:
            product.view_count += 1
        else:
            product.view_count = 1
        product.save()
    context = {'product': product}
    return render(request, 'market/Product_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- market CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>충대마켓</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
<a href="{% url 'market:liked_products' %}" style="position:fixed; top:80px; right:20px; border: 1px solid #007bff; padding: 8px; border-radius: 5px; text-decoration: none; color: white; background-color: #007bff; font-size: 14px; line-height: 1.8; text-align: center; display: block;">
    찜한상품<br>
    <span style="color: red;">&#9829;</span>
    {{ request.user.liked_products.count }}
</a>

{% if user.is_authenticated %}
{% endif %}
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<nav class="navbar navbar-dark bg-primary">
  <div class="container-fluid d-flex justify-content-between">
    <form class="d-flex">
      <a class="navbar-brand mx-3" href="{% url 'market:index' %}"><strong>충대마켓</strong></a>
    </form>
    <form class="d-flex">
      <div class="input-group">
        <input class="form-control" type="text" id="search_kw" placeholder="어떤 상품을 찾으시나요?" aria-label="Search" style="width:300px;" value="{{ kw|default_if_none:'' }}">
        <div class="input-group-append">
          <button class="btn btn-dark" type="button" id="btn_search">검색</button>
        </div>
      </div>
    </form>
    <form id="searchForm" method="get" action="{% url 'index' %}">
      <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
      <input type="hidden" id="page" name="page" value="{{ page }}">
    </form>
    {% if user.is_authenticated %}
    <a class="nav-link" href="{% url 'common:profile' user.pk %}" style="color:white;">마이페이지</a>
    <a class="nav-link" href="{% url 'common:logout' %}" style="color:white;">로그아웃</a>
    {% else %}
    <a class="nav-link" href="{% url 'common:login' %}" style="color:white;">로그인</a>
    <a class="nav-link" href="{% url 'common:signup' %}" style="color:white;">회원가입</a>
    {% endif %}
  </div>
</nav>